# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_times', models.DateTimeField()),
                ('taken_times', models.DateTimeField(null=True)),
                ('taken', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entered', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Case')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Rx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('info', models.TextField()),
                ('date_prescribed', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('drug', models.CharField(max_length=100)),
                ('adherence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Adherence')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Note'),
        ),
        migrations.AddField(
            model_name='case',
            name='rxs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Rx'),
        ),
    ]
