# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rx',
            name='adherence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Adherence'),
        ),
    ]
